# Generated by Django 2.1.3 on 2018-11-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_contacts', '0002_auto_20181128_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='person',
            field=models.ManyToManyField(null=True, to='my_contacts.Person'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='mail',
            field=models.EmailField(max_length=64, null=True),
        ),
    ]
